export enum DocumentStatus {
  DRAFT = 'DRAFT',
  PENDING_ROLE_2_SIGNATURE = 'PENDING_ROLE_2_SIGNATURE',
  PENDING_ROLE_3_SIGNATURE = 'PENDING_ROLE_3_SIGNATURE',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum SignerRole {
  ROLE_1 = 'ROLE_1',
  ROLE_2 = 'ROLE_2',
  ROLE_3 = 'ROLE_3',
}

export enum FieldType {
  SIGNATURE = 'SIGNATURE',
  NAME = 'NAME',
  DATE = 'DATE',
  EMAIL = 'EMAIL',
}

export enum WorkflowStep {
  ROLE_1 = 'ROLE_1',
  ROLE_2 = 'ROLE_2',
  AWAITING_ROLE_3_EMAIL = 'AWAITING_ROLE_3_EMAIL',
  ROLE_3 = 'ROLE_3',
  COMPLETED = 'COMPLETED',
}

export const ROLE_3_PLACEHOLDER_EMAIL = 'role3.placeholder@pending.local';

export enum AuditAction {
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  SIGNATURE_TAG_ADDED = 'SIGNATURE_TAG_ADDED',
  WORKFLOW_CREATED = 'WORKFLOW_CREATED',
  SENT_TO_ROLE_2 = 'SENT_TO_ROLE_2',
  ROLE_2_SIGNED = 'ROLE_2_SIGNED',
  ROLE_3_EMAIL_UPDATED = 'ROLE_3_EMAIL_UPDATED',
  SENT_TO_ROLE_3 = 'SENT_TO_ROLE_3',
  ROLE_3_SIGNED = 'ROLE_3_SIGNED',
  WORKFLOW_COMPLETED = 'WORKFLOW_COMPLETED',
}